// Builds the self-hosted font set and the @font-face rules that go with it.
//
// The site used to pull five families from fonts.googleapis.com on every visit, which meant two
// extra connections before first paint and no chance of the invitation opening offline. Everything
// now ships from our own origin:
//
//   * the Latin faces are copied straight out of @fontsource, split latin / latin-ext so a browser
//     only fetches latin-ext when a guest's name actually needs it
//   * Noto Naskh Arabic is cut down to the Qur'anic verse and the bismillah — the only Arabic the
//     face ever renders here — which takes it from 51 KB to about 12
//   * Noto Nastaliq Urdu is split in two: `nastaliq-core` carries just the Sindhi flourishes that
//     show while the site is in English (the bismillah, the couple's names, the closing line), and
//     the full Sindhi cut is fetched only when a reader switches to سنڌي
//
// Run `npm run fonts` after changing any Sindhi string. The woff2 output is committed, so an
// ordinary `npm run build` needs neither python nor the @fontsource packages.
import { copyFileSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "src/assets/fonts");
const mod = (p) => resolve(root, "node_modules/@fontsource", p);
mkdirSync(out, { recursive: true });

const ranges = (pkg) => JSON.parse(readFileSync(mod(`${pkg}/unicode.json`), "utf8"));
const k = (n) => (n / 1024).toFixed(1).padStart(6) + " KB";

/* ── 1 · Latin faces, copied as-is ─────────────────────────────────────────── */

const EAGER = [
  { pkg: "cormorant-garamond", family: "Cormorant Garamond",
    faces: [[300,"normal"],[300,"italic"],[400,"normal"],[400,"italic"],[600,"normal"]],
    subsets: ["latin", "latin-ext"],
    // italics only ship in the latin cut; a latin-ext italic is 22 KB for characters no guest name needs
    skip: (s, style) => s === "latin-ext" && style === "italic" },
  { pkg: "cormorant-sc", family: "Cormorant SC",
    faces: [[600,"normal"],[700,"normal"]], subsets: ["latin", "latin-ext"] },
  { pkg: "italianno", family: "Italianno",
    faces: [[400,"normal"]], subsets: ["latin", "latin-ext"] },
];

let css = "/* Generated by scripts/build-fonts.mjs — do not edit by hand. */\n";
let eagerLatin = 0;

for (const { pkg, family, faces, subsets, skip } of EAGER) {
  const uni = ranges(pkg);
  for (const subset of subsets) {
    for (const [weight, style] of faces) {
      if (skip?.(subset, style)) continue;
      const name = `${pkg}-${subset}-${weight}-${style}.woff2`;
      copyFileSync(mod(`${pkg}/files/${name}`), resolve(out, name));
      const size = statSync(resolve(out, name)).size;
      if (subset === "latin") eagerLatin += size;
      css += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;` +
             `src:url(./assets/fonts/${name}) format('woff2');unicode-range:${uni[subset]}}\n`;
    }
  }
}

/* ── 2 · Arabic-script subsets ─────────────────────────────────────────────── */

// Pulled from the source of truth rather than a hand-kept list, so a newly added Sindhi string
// can never quietly fall outside the subset and render in a fallback face.
// config.js is in here because RSVP_BY carries a Sindhi date the moment the family sets one, and
// a deadline rendered in a fallback face would be the first thing a guest reads.
const sources = ["src/i18n.js", "src/App.jsx", "src/config.js",
  ...readdirSync(resolve(root, "src/components")).map((f) => `src/components/${f}`)];
const corpus = sources.map((f) => readFileSync(resolve(root, f), "utf8")).join("");
const arabicOf = (s) => (s.match(/[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]/gu) || []).join("");

// digits, the separators that sit inside Sindhi runs, and the combining marks the text carries
const EXTRA = "0123456789٠١٢٣٤٥٦٧٨٩ ·—…،؛؟:.!‌‍";
const ALL = [...new Set(arabicOf(corpus))].join("") + EXTRA;
const CORE = [...new Set(arabicOf("بسم الله الرحمٰن الرحيم تاشقين ۽ انوشا دعائن سان"))].join("") + EXTRA;

const subset = (src, dst, text) => {
  execFileSync("python3", ["-m", "fontTools.subset", src,
    `--text=${text}`,
    "--layout-features=*",        // Nastaliq is almost entirely GSUB; dropping features breaks joining
    "--notdef-outline", "--drop-tables+=DSIG",
    "--flavor=woff2", `--output-file=${dst}`], { stdio: ["ignore", "ignore", "inherit"] });
  return statSync(dst).size;
};

const naskhSrc = mod("noto-naskh-arabic/files/noto-naskh-arabic-arabic-400-normal.woff2");
const naskh = subset(naskhSrc, resolve(out, "naskh-arabic-400.woff2"), ALL);
css += `@font-face{font-family:'Noto Naskh Arabic';font-style:normal;font-weight:400;font-display:swap;` +
       `src:url(./assets/fonts/naskh-arabic-400.woff2) format('woff2')}\n`;

const nastaliq = (w) => mod(`noto-nastaliq-urdu/files/noto-nastaliq-urdu-arabic-${w}-normal.woff2`);
const core = subset(nastaliq(400), resolve(out, "nastaliq-core.woff2"), CORE);
css += `@font-face{font-family:'Nastaliq Core';font-style:normal;font-weight:400;font-display:swap;` +
       `src:url(./assets/fonts/nastaliq-core.woff2) format('woff2')}\n`;

// Not declared here — App.jsx loads these through the FontFace API the moment Sindhi is chosen.
const sd400 = subset(nastaliq(400), resolve(out, "nastaliq-400.woff2"), ALL);
const sd600 = subset(nastaliq(600), resolve(out, "nastaliq-600.woff2"), ALL);

writeFileSync(resolve(root, "src/fonts.css"), css);

const before = statSync(nastaliq(400)).size + statSync(nastaliq(600)).size + statSync(naskhSrc).size;
console.log(`latin (first paint)   ${k(eagerLatin)}`);
console.log(`naskh arabic          ${k(naskh)}   ← ${k(statSync(naskhSrc).size)}`);
console.log(`nastaliq core         ${k(core)}   ← ${k(statSync(nastaliq(400)).size)}`);
console.log(`  english first paint ${k(eagerLatin + naskh + core)}`);
console.log(`nastaliq sindhi 400   ${k(sd400)}`);
console.log(`nastaliq sindhi 600   ${k(sd600)}   ← ${k(statSync(nastaliq(600)).size)}`);
console.log(`  sindhi total        ${k(eagerLatin + naskh + core + sd400 + sd600)}`);
console.log(`arabic faces cut from ${k(before)} to ${k(naskh + core + sd400 + sd600)}`);
