// Writes docs/sw.js after the Vite build, with the built file list baked in.
//
// Two reasons this exists. Guests open the invitation at the hall, where the signal is whatever
// it is; and guests travelling up from Karachi open it on the road. Once the page has been seen
// once it should open again with no network at all — and, being installable, sit on a home screen
// instead of being lost in a WhatsApp thread.
//
// Everything the build emits is precached except the 2.1 MB print card, which is far too heavy to
// push onto a phone up front — that one is cached the first time a guest opens or saves it.
import { createHash } from "node:crypto";
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const docs = resolve(root, "docs");

const RUNTIME_ONLY = [
  "assets/card-print.png",  // 2.1 MB; cached the first time a guest opens or saves it
  "assets/og-card.jpg",    // only ever fetched by link-preview crawlers, never by the page
];

const walk = (dir) => readdirSync(dir).flatMap((name) => {
  const full = join(dir, name);
  return statSync(full).isDirectory() ? walk(full) : [relative(docs, full).split("\\").join("/")];
});

const files = walk(docs)
  .filter((f) => f !== "sw.js" && !RUNTIME_ONLY.includes(f))
  .sort();

// the cache name changes whenever any built file does, which is what evicts the previous version
const version = createHash("sha256").update(files.join("\n")).digest("hex").slice(0, 12);
const precache = ["./", ...files.map((f) => "./" + f)];

const sw = `// Generated by scripts/gen-sw.mjs — do not edit by hand.
const CACHE = "ta-${version}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations serve the cached shell straight away and refresh it behind the reader, so a
  // personalised ?to= link still opens instantly with no network.
  if (request.mode === "navigate") {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = await cache.match("./", { ignoreSearch: true });
      const fresh = fetch(request).then((r) => {
        if (r.ok) cache.put("./", r.clone());
        return r;
      }).catch(() => shell);
      return shell || fresh;
    })());
    return;
  }

  // Everything else: cache first (the build's filenames are content-hashed), network on a miss,
  // and whatever comes back gets kept — that is how the print card lands in the cache.
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request, { ignoreSearch: false });
    if (hit) return hit;
    try {
      const res = await fetch(request);
      if (res.ok && res.type === "basic") cache.put(request, res.clone());
      return res;
    } catch (err) {
      const any = await cache.match(request, { ignoreSearch: true });
      if (any) return any;
      throw err;
    }
  })());
});
`;

writeFileSync(resolve(docs, "sw.js"), sw);
const bytes = precache.slice(1).reduce((n, f) => n + statSync(resolve(docs, f.slice(2))).size, 0);
console.log(`sw.js  cache ta-${version}  ${precache.length} entries  ${(bytes / 1024).toFixed(0)} KB precached`);
